dirs: ./mock
watch: true
cors:
  origin: true
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD']
  allowedHeaders: ['Authorization', 'Content-Type']
port: 3000
proxy:
  prefix: /error
  upstream: https://hook.bearychat.com