language: node_js
node_js:
- '10'
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
script:
- npm run lint
- npm test
after_success:
- npm run build-ci
- npm run upload
git:
  depth: 1
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: script
  script: bash echo todo
  skip_cleanup: true
  on:
    tags: true
    repo: ta7sudan/blog-mobile
    branch: master
